### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by pinpins** [SmartCash/Core-Smart#25]
wallet synced up until last block as per block explorer
though still giving error on getblocktemplate
error -10: smartcash is syncing with network...

getinfo
{
    "version": 1020300,
    "protocolversion": 90026,
    "walletversion": 130000,
    "balance": 0,
    "blocks": 548414,
    "timeoffset": 0,
    "connections": 8,
    "proxy": "",
    "difficulty": 61347.85184762,
    "testnet": false,
    "keypoololdest": "2018-07-09 10:11:01 +0300",
    "keypoolsize": 199,
    "paytxfee": 0,
    "relayfee": 0.001,
    "errors": ""
}

getblocktemplate
error -10: smartcash is syncing with network...

**Comment by xdustinface** [comment]
Thats no issue..there is more than only block syncing to be done on startup. What you noticed is related to the nodelist/winnerslist sync. If you check `snsync status` you will see when your daemon is entirely synced with the network.
