### ISSUE TITLE
build fails with --disable-wallet configure switch

### ISSUE THREAD

**Issue by jazy510** [SmartCash/Core-Smart#28]
Attempting to make with the --disable-wallet option, yields errors.

**Comment by thesolarminer** [comment]
The wallet is needed for processing legacy data.  You can run with litemode=1 in the config file to run without SmartNode features.

**Comment by jazy510** [comment]
wouldn't it make more sense to remove the switch's functionality, rather than allow it to create a makefile that won't build?
