### ISSUE TITLE
Smartreward corruption, too long to rebuild -- sugestion of solution

### ISSUE THREAD

**Issue by tconrado** [SmartCash/Core-Smart#41]
Smartrewards is a unique feature from Smartcash, and shall be treated in with the very same importance of the wallet.dat of bitcoin. 

Thus, I would like to suggest the creation of a checkpoint.
Every n blocks, the daemon will create a copy of the smartrewards database.
If an expected and improper shutdown happen (ie. the usage suggestion includes a dedicated and non trustworthy VPS) the systemd may restart and the daemon can resume the smartrewards from the checkpoint, instead starting from ground zero

**Comment by xdustinface** [comment]
Thanks for the suggestion. We are already working on a solution for this. There is a branch called "smartreward-improvements" which brings some changes to the creation of the SmartReward database to avoid the recreation after a crash and also give the whole SmartReward processing better performance.
