### ISSUE TITLE
Questions about upgrading from 1.2.8 to 1.3.0

### ISSUE THREAD

**Issue by apufvqsp** [SmartCash/Core-Smart#72]
Regarding the 1.3.0 version upgrade, I have the following three questions
1. Is there any change in the rpc interface, if so, what are the specific details of the change?
2. Can you explain the time lock?
3. Among the transaction data obtained through the rpc interface, from which items can it be determined that the transaction is time-locked?
4. Can the address in the legacy format continue to be used?

thank you very much

**Comment by thesolarminer** [comment]
RPC stays the same.  We added the SAPI which is an external way to access the blockchain on port 8080 to get balance from an address, unspent inputs, and send a transaction.  sapi=0 will disable it and take up less disk space.

Timelock is a feature that doesn't allow spending of an address until a specific time or block number.

To find the time a transaction unlocks you can get do something like this example. 
./smartcash-cli decoderawtransaction $(./smartcash-cli getrawtransaction f8e31fbf8303b29685489877d3f61c6e8598f9b1dfb4f9b24661ce1f5a8e1f8c) | grep locktime
if the number is less than 500,000,000 then it is a block number.  If it is over it is unix time

Yes, legacy addresses are encouraged to continue to be used on this release.

**Comment by apufvqsp** [comment]
thank you for your reply

Is the timelock implemented by samrt-core different from the timelock of bitcoin-core?

`The Bitcoin transaction lock time is the time at which a particular transaction can be added to the blockchain. This is the earliest time that miners can include the transaction in their hashing of the Merkle root to attach it in the latest block to the blockchain.

There are two specific types of transaction locktime. Firstly when the locktime figure is less than 500 million it is interpreted as a blockheight and miners therefore have to wait until that block height has been reached before attempting to include it in a block.

If it is above 500 million it is converted to a unix timestamp – a unix timestamp being the number of seconds since January 1st 1970.`

https://www.cryptocompare.com/coins/guides/what-is-bitcoin-transaction-locktime/

**Comment by thesolarminer** [comment]
My mistake.  Timelock is not the correct field.
The asm field will have a number before the OP_CHECKLOCKTIMEVERIFY if it has a timelock setting.  That number is either a block number if less than 500,000,000 or unix time if above.
      "scriptPubKey": {
        "asm": "19000 OP_CHECKLOCKTIMEVERIFY OP_DROP OP_DUP OP_HASH160 

It will also show this if you just want to flag if locked or not.
"type": "pubkeyhashlocked",

**Comment by apufvqsp** [comment]
OK, thank you for your patience
