### ISSUE TITLE
Wallet 2.0.2 Stuck connecting to peers

### ISSUE THREAD

**Issue by cannycookie** [SmartCash/Core-Smart#94]
Hi Guys,

I've updated to OSX wallet 2.0.2 but it still says connecting to peers.  I've tried deleting peers.dat and rerunning but no luck.

Any suggestions as to what to do next?

Also my linux node says:-
```
./smartcash-cli smartnode status
{
  "outpoint": "COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295)",
  "service": "[::]:0",
  "status": "Node just started, not yet activated"
}
```
Tried this command:-
```./smartcash-cli reconsiderblock $(./smartcash-cli getblockhash 2025813)```

but getting:-
```
error code: -8
error message:
Block height out of range
error code: -1
error message:
reconsiderblock "hash"

Removes invalidity status of a block and its descendants, reconsider them for activation.
This can be used to undo the effects of invalidateblock.
```

**Comment by camakin** [comment]
Hi cannycookie

If you check Discord support they can maybe help.
https://discord.gg/TPZbdn3J

You could try adding nodes

addnode 167.86.124.250 add
addnode 167.86.124.240 add
addnode 185.216.231.73 add
addnode 135.181.85.182 add
addnode 173.249.21.162 add
addnode 71.45.87.12 add

**Comment by thesolarminer** [comment]
Addnodes are not the issue.

You reconsidered the wrong block.  ./smartcash-cli getblockcount and put that block number at the end of the reconsider command you used.  If that doesn't work start with -reindex.
